services:
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS zeeguu_test;" -uroot
  - mysql -e "grant all on zeeguu_test.* to 'zeeguu_test'@'localhost' identified by 'zeeguu_test';" -uroot
  - mkdir -p ~/.config/zeeguu/ && cp testing_default.cfg ~/.config/zeeguu/core_test.cfg
  - pip install readability
  - pip install readability_lxml
  - python -c "from readability.readability import Document"

language: python
python:
  - "3.6"

install: "python setup.py install"

script: "./run_tests.sh"
