before_install:
  - pip3 install -r requirements.txt

language: python
python:
  - "3.6"
cache:
  pip: true
  directories:
   - $HOME/virtualenv

env:

install: "python3 setup.py install"

script: coverage run --source zeeguu -m unittest discover

after_success:
  coveralls
